<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="2" ignored="1" total="6" passed="1">
  <reporter-output>
    <line>
      <![CDATA[<a target="_blank" href="F:\screenshot\error.jpg">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="F:\screenshot\error.jpg"><img height=200 width=200 src="F:\screenshot\error.jpg"></a>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="F:\screenshot\error.jpg">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="F:\screenshot\error.jpg"><img height=200 width=200 src="F:\screenshot\error.jpg"></a>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="F:\screenshot\error.jpg">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="F:\screenshot\error.jpg"><img height=200 width=200 src="F:\screenshot\error.jpg"></a>]]>
    </line>
  </reporter-output>
  <suite name="TestNG Learning" duration-ms="164" started-at="2019-04-14T06:02:58Z" finished-at="2019-04-14T06:02:58Z">
    <groups>
      <group name="high">
        <method signature="TestCase2.validateTitles()[pri:0, instance:testnglearning.TestCase2@5faeada1]" name="validateTitles" class="testnglearning.TestCase2"/>
        <method signature="TestCase3.doUserReg()[pri:1, instance:testnglearning.TestCase3@76b0bfab]" name="doUserReg" class="testnglearning.TestCase3"/>
        <method signature="TestCase3.doLogin()[pri:2, instance:testnglearning.TestCase3@76b0bfab]" name="doLogin" class="testnglearning.TestCase3"/>
      </group> <!-- high -->
      <group name="low">
        <method signature="TestCase1.doLogin()[pri:2, instance:testnglearning.TestCase1@1f7030a6]" name="doLogin" class="testnglearning.TestCase1"/>
      </group> <!-- low -->
      <group name="med">
        <method signature="TestCase3.doUserReg()[pri:1, instance:testnglearning.TestCase3@76b0bfab]" name="doUserReg" class="testnglearning.TestCase3"/>
        <method signature="TestCase3.doLogin()[pri:2, instance:testnglearning.TestCase3@76b0bfab]" name="doLogin" class="testnglearning.TestCase3"/>
        <method signature="TestCase3.isSkip()[pri:3, instance:testnglearning.TestCase3@76b0bfab]" name="isSkip" class="testnglearning.TestCase3"/>
      </group> <!-- med -->
    </groups>
    <test name="Login Test" duration-ms="62" started-at="2019-04-14T06:02:58Z" finished-at="2019-04-14T06:02:58Z">
      <class name="testnglearning.TestCase1">
        <test-method status="PASS" signature="createDbConn()[pri:0, instance:testnglearning.TestCase1@1f7030a6]" name="createDbConn" is-config="true" duration-ms="17" started-at="2019-04-14T06:02:58Z" finished-at="2019-04-14T06:02:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDbConn -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testnglearning.TestCase1@1f7030a6]" name="launchBrowser" is-config="true" duration-ms="0" started-at="2019-04-14T06:02:58Z" finished-at="2019-04-14T06:02:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="doLogin()[pri:2, instance:testnglearning.TestCase1@1f7030a6]" name="doLogin" duration-ms="9" started-at="2019-04-14T06:02:58Z" finished-at="2019-04-14T06:02:58Z">
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="F:\screenshot\error.jpg">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="F:\screenshot\error.jpg"><img height=200 width=200 src="F:\screenshot\error.jpg"></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="quitBrowser()[pri:0, instance:testnglearning.TestCase1@1f7030a6]" name="quitBrowser" is-config="true" duration-ms="0" started-at="2019-04-14T06:02:58Z" finished-at="2019-04-14T06:02:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
        <test-method status="PASS" signature="closeDbConn()[pri:0, instance:testnglearning.TestCase1@1f7030a6]" name="closeDbConn" is-config="true" duration-ms="0" started-at="2019-04-14T06:02:58Z" finished-at="2019-04-14T06:02:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDbConn -->
      </class> <!-- testnglearning.TestCase1 -->
    </test> <!-- Login Test -->
    <test name="Validate Title Test" duration-ms="17" started-at="2019-04-14T06:02:58Z" finished-at="2019-04-14T06:02:58Z">
      <class name="testnglearning.TestCase2">
        <test-method status="FAIL" signature="validateTitles()[pri:0, instance:testnglearning.TestCase2@5faeada1]" name="validateTitles" duration-ms="9" started-at="2019-04-14T06:02:58Z" finished-at="2019-04-14T06:02:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Yahoo.com] but found [Gmail.com],
Element not found expected [true] but found [false],
Test failed as the condition is not met]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Yahoo.com] but found [Gmail.com],
Element not found expected [true] but found [false],
Test failed as the condition is not met
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at testnglearning.TestCase2.validateTitles(TestCase2.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="F:\screenshot\error.jpg">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="F:\screenshot\error.jpg"><img height=200 width=200 src="F:\screenshot\error.jpg"></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateTitles -->
      </class> <!-- testnglearning.TestCase2 -->
    </test> <!-- Validate Title Test -->
    <test name="Dependency Test" duration-ms="29" started-at="2019-04-14T06:02:58Z" finished-at="2019-04-14T06:02:58Z">
      <class name="testnglearning.TestCase3">
        <test-method status="FAIL" signature="doUserReg()[pri:1, instance:testnglearning.TestCase3@76b0bfab]" name="doUserReg" duration-ms="4" started-at="2019-04-14T06:02:58Z" finished-at="2019-04-14T06:02:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User not registered successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User not registered successfully
at org.testng.Assert.fail(Assert.java:96)
at testnglearning.TestCase3.doUserReg(TestCase3.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="F:\screenshot\error.jpg">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="F:\screenshot\error.jpg"><img height=200 width=200 src="F:\screenshot\error.jpg"></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="SKIP" signature="doLogin()[pri:2, instance:testnglearning.TestCase3@76b0bfab]" name="doLogin" duration-ms="0" started-at="2019-04-14T06:02:58Z" depends-on-methods="testnglearning.TestCase3.doUserReg" finished-at="2019-04-14T06:02:58Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase3.doLogin()[pri:2, instance:testnglearning.TestCase3@76b0bfab] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase3.doLogin()[pri:2, instance:testnglearning.TestCase3@76b0bfab] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="SKIP" signature="isSkip()[pri:3, instance:testnglearning.TestCase3@76b0bfab]" name="isSkip" duration-ms="2" started-at="2019-04-14T06:02:58Z" finished-at="2019-04-14T06:02:58Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test as the condition is not met]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test as the condition is not met
at testnglearning.TestCase3.isSkip(TestCase3.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isSkip -->
      </class> <!-- testnglearning.TestCase3 -->
    </test> <!-- Dependency Test -->
  </suite> <!-- TestNG Learning -->
</testng-results>
