<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="rajanpc" name="Default test" tests="17" failures="2" timestamp="18 Jul 2016 10:35:20 GMT" time="0.102" errors="0">
  <testcase name="testLogin" time="0.005" classname="DemoTestCases.DemoTestCase1"/>
  <testcase name="testRegistration" time="0.001" classname="DemoTestCases.DemoTestCase1"/>
  <testcase name="demoFailAnotherTest" time="0.005" classname="DemoTestCases.DemoTestCase6">
    <failure type="java.lang.AssertionError" message="DemoTestCase6=&amp;gt;It has been failed, because condition is not met expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: DemoTestCase6=>It has been failed, because condition is not met expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at DemoTestCases.DemoTestCase6.demoFailAnotherTest(DemoTestCase6.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- demoFailAnotherTest -->
  <testcase name="demoFailTest" time="0.002" classname="DemoTestCases.DemoTestCase6">
    <failure type="java.lang.AssertionError" message="expected [DemoTestCase6_bye] but found [DemoTestCase6_hello]">
      <![CDATA[java.lang.AssertionError: expected [DemoTestCase6_bye] but found [DemoTestCase6_hello]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at DemoTestCases.DemoTestCase6.demoFailTest(DemoTestCase6.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- demoFailTest -->
  <testcase name="demoPassTest" time="0.001" classname="DemoTestCases.DemoTestCase6"/>
  <testcase name="demoSkipTest" time="0.002" classname="DemoTestCases.DemoTestCase6">
    <skipped/>
  </testcase> <!-- demoSkipTest -->
  <testcase name="isSignUpButtonVisible" time="0.002" classname="DemoTestCases.DemoTestCase5"/>
  <testcase name="isWebGuiVisible" time="0.002" classname="DemoTestCases.DemoTestCase5"/>
  <testcase name="isRegistrationGUIVisible" time="0.002" classname="DemoTestCases.DemoTestCase5"/>
  <testcase name="testRegistration" time="0.002" classname="DemoTestCases.DemoTestCase5"/>
  <testcase name="testLogin" time="0.001" classname="DemoTestCases.DemoTestCase5"/>
  <testcase name="testRegistration" time="0.002" classname="DemoTestCases.DemoTestCase4"/>
  <testcase name="testLogin" time="0.002" classname="DemoTestCases.DemoTestCase4"/>
  <testcase name="testRegistration" time="0.002" classname="DemoTestCases.DemoTestCase3"/>
  <testcase name="testLogin" time="0.001" classname="DemoTestCases.DemoTestCase3"/>
  <testcase name="testRegistration" time="0.001" classname="DemoTestCases.DemoTestCase2"/>
  <testcase name="testLogin" time="0.001" classname="DemoTestCases.DemoTestCase2"/>
</testsuite> <!-- Default test -->
